/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pemesananlapanganfutsal;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Patrick
 */
public class editpenjaga extends javax.swing.JFrame {

    /**
     * Creates new form editpenjaga
     */
    MenuManager mm;
    Penjaga p;

    public editpenjaga(SistemLapangan sys) {
        initComponents();
        Controller c = new Controller();
        c.setModel(sys);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textInputID = new javax.swing.JTextField();
        textNewID = new javax.swing.JTextField();
        textNewNama = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTampil = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        listPenjaga = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("EDIT PENJAGA");

        jLabel2.setText("Input ID                  :");

        jLabel3.setText("Input new ID           :");

        jLabel4.setText("Input new Nama      :");

        btnSubmit.setText("Submit");

        btnBack.setText("Back");

        areaTampil.setColumns(20);
        areaTampil.setRows(5);
        jScrollPane1.setViewportView(areaTampil);

        jScrollPane2.setViewportView(listPenjaga);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textInputID, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                    .addComponent(textNewID)
                                    .addComponent(textNewNama)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSubmit)
                                .addGap(18, 18, 18)
                                .addComponent(btnBack)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textInputID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textNewID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textNewNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBack)
                            .addComponent(btnSubmit)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTampil;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listPenjaga;
    private javax.swing.JTextField textInputID;
    private javax.swing.JTextField textNewID;
    private javax.swing.JTextField textNewNama;
    // End of variables declaration//GEN-END:variables

    public void addListener(ActionListener e) {
        btnBack.addActionListener(e);
        btnSubmit.addActionListener(e);
        textInputID.addActionListener(e);
        textNewID.addActionListener(e);
        textNewNama.addActionListener(e);
    }

    private class Controller implements ActionListener {

        private SistemLapangan sys;

        public Controller() {
            addListener(this);
        }

        public void setModel(SistemLapangan sys) {
            this.sys = sys;
        }

        @Override
        public void actionPerformed(ActionEvent ae) {
            Object source = ae.getSource();
            if (source.equals(btnBack)) {
                mm = new MenuManager(sys);
                mm.setVisible(true);
                setVisible(false);
            } else if (source.equals(btnSubmit)) {
                try {
                    String idl = "";
                    idl = textInputID.getText();
                    if (idl.length() < 10 && idl.length() > 10) {
                        JOptionPane.showMessageDialog(null, "ID Penjaga Harus 10 Karakter", "Warning", JOptionPane.WARNING_MESSAGE);
                    } else {
                        String idb = textNewID.getText();
                        String namab = textNewNama.getText();
                        sys.editPenjaga(idl, idb, namab);
                        JOptionPane.showMessageDialog(null, "Nama dan ID Penjaga berhasil di edit", "Success", JOptionPane.INFORMATION_MESSAGE);
                        mm = new MenuManager(sys);
                        mm.setVisible(true);
                        setVisible(false);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "ID Penjaga tidak ditemukan", "Warning", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
    }
}
