/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pemesananlapanganfutsal;

import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author asus
 */
public class MenuPenjaga extends javax.swing.JFrame {

    MenuAddMember mam;
    MenuHapusMember mhm;
    MenuCariMember mcm;
    MenuEditMember mem;
    MenuViewMember mvm;
    MenuUtama mu;
    MenuCarijadwal mcj;
    MenuHapusJadwal mhj;
    MenuTambahJadwal mtj;
    MenuViewJadwal mvj;
    MenuPembayaran mnp;

    /**
     * Creates new form LoginPenjaga
     */
    public MenuPenjaga(SistemLapangan sys) {
        initComponents();
        Controller c = new Controller();
        c.setModel(sys);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnTambahMember = new javax.swing.JButton();
        btnHapusMember = new javax.swing.JButton();
        btnCarisMember = new javax.swing.JButton();
        btnEditMember = new javax.swing.JButton();
        btnViewMember = new javax.swing.JButton();
        btnTambahJadwal = new javax.swing.JButton();
        btnHapusJadwal = new javax.swing.JButton();
        btnCariJadwal = new javax.swing.JButton();
        btnPembayaran = new javax.swing.JButton();
        btnViewJadwal = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Menu Penjaga");

        btnTambahMember.setText("Tambah Member");

        btnHapusMember.setText("Hapus Member");
        btnHapusMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusMemberActionPerformed(evt);
            }
        });

        btnCarisMember.setText("Cari Member");
        btnCarisMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarisMemberActionPerformed(evt);
            }
        });

        btnEditMember.setText("Edit Member");
        btnEditMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditMemberActionPerformed(evt);
            }
        });

        btnViewMember.setText("View Member");
        btnViewMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMemberActionPerformed(evt);
            }
        });

        btnTambahJadwal.setText("Tambah Jadwal");
        btnTambahJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahJadwalActionPerformed(evt);
            }
        });

        btnHapusJadwal.setText("Hapus Jadwal");
        btnHapusJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusJadwalActionPerformed(evt);
            }
        });

        btnCariJadwal.setText("Cari Jadwal");
        btnCariJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariJadwalActionPerformed(evt);
            }
        });

        btnPembayaran.setText("Pembayaran");
        btnPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembayaranActionPerformed(evt);
            }
        });

        btnViewJadwal.setText("View Jadwal");
        btnViewJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewJadwalActionPerformed(evt);
            }
        });

        btnLogOut.setText("Log Out");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(158, 158, 158))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogOut))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTambahMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHapusMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCarisMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTambahJadwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHapusJadwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewJadwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCariJadwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTambahMember)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapusMember)
                        .addGap(18, 18, 18)
                        .addComponent(btnCarisMember)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewMember)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditMember))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTambahJadwal)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapusJadwal)
                        .addGap(18, 18, 18)
                        .addComponent(btnCariJadwal)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewJadwal)
                        .addGap(18, 18, 18)
                        .addComponent(btnPembayaran)))
                .addGap(17, 17, 17)
                .addComponent(btnLogOut))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnHapusMemberActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void btnCarisMemberActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void btnEditMemberActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void btnViewMemberActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void btnHapusJadwalActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void btnCariJadwalActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void btnPembayaranActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void btnViewJadwalActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void btnTambahJadwalActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    /**
     * @param args the command line arguments
     */
    public void addListener(ActionListener e) {
        btnCarisMember.addActionListener(e);
        btnEditMember.addActionListener(e);
        btnTambahMember.addActionListener(e);
        btnViewMember.addActionListener(e);
        btnHapusMember.addActionListener(e);
        btnCariJadwal.addActionListener(e);
        btnHapusJadwal.addActionListener(e);
        btnViewJadwal.addActionListener(e);
        btnTambahJadwal.addActionListener(e);
        btnPembayaran.addActionListener(e);
        btnLogOut.addActionListener(e);
    }

    private class Controller implements ActionListener {

        private SistemLapangan sys;

        public Controller() {
            addListener(this);
        }

        public void setModel(SistemLapangan sys) {
            this.sys = sys;
        }

        @Override
        public void actionPerformed(ActionEvent ae) {
            Object source = ae.getSource();
            if (source.equals(btnLogOut)) {
                JOptionPane.showMessageDialog(null, "TERIMAKASIH PENJAGA", "", JOptionPane.INFORMATION_MESSAGE);
                mu = new MenuUtama(sys);
                mu.setVisible(true);
                setVisible(false);
            } else if (source.equals(btnTambahMember)) {
                mam = new MenuAddMember(sys);
                mam.setVisible(true);
                setVisible(false);
            } else if (source.equals(btnHapusMember)) {
                mhm = new MenuHapusMember(sys);
                mhm.setVisible(true);
                setVisible(false);
            } else if (source.equals(btnEditMember)) {
                mem = new MenuEditMember(sys);
                mem.setVisible(true);
                setVisible(false);

            } else if (source.equals(btnCarisMember)) {
                mcm = new MenuCariMember(sys);
                mcm.setVisible(true);
                setVisible(false);
            } else if (source.equals(btnViewMember)) {
                mvm = new MenuViewMember(sys);
                mvm.setVisible(true);
                setVisible(false);
            } else if (source.equals(btnTambahJadwal)) {
                mtj = new MenuTambahJadwal(sys);
                mtj.setVisible(true);
                setVisible(false);
                
            } else if (source.equals(btnCariJadwal)) {
                mcj = new MenuCarijadwal(sys);
                mcj.setVisible(true);
                setVisible(false);
            } else if (source.equals(btnViewJadwal)) {
                mvj = new MenuViewJadwal(sys);
                mvj.setVisible(true);
                setVisible(false);
            } else if (source.equals(btnHapusJadwal)) {
                mhj = new MenuHapusJadwal(sys);
                mhj.setVisible(true);
                setVisible(false);
            } else if (source.equals(btnPembayaran)) {
                mnp = new MenuPembayaran(sys);
                mnp.setVisible(true);
                setVisible(false);
            }
        }
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnCariJadwal;
    private javax.swing.JButton btnCarisMember;
    private javax.swing.JButton btnEditMember;
    private javax.swing.JButton btnHapusJadwal;
    private javax.swing.JButton btnHapusMember;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnPembayaran;
    private javax.swing.JButton btnTambahJadwal;
    private javax.swing.JButton btnTambahMember;
    private javax.swing.JButton btnViewJadwal;
    private javax.swing.JButton btnViewMember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}

