/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pemesananlapanganfutsal;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author uthasuryo
 */
public class MenuHapusJadwal extends javax.swing.JFrame {
    MenuPenjaga mp;
    /**
     * Creates new form MenuHapusJadwal
     */
    public MenuHapusJadwal(SistemLapangan sys) {
        initComponents();
        Controller c = new Controller();
        c.setModel(sys);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfIdCari = new javax.swing.JTextField();
        btnHapusJadwal = new javax.swing.JButton();
        btnCancelHapusJadwal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Hapus Jadwal");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Masukkan ID Jadwal yang akan di hapus");

        btnHapusJadwal.setText("Hapus");

        btnCancelHapusJadwal.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(149, 149, 149))
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel2)
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfIdCari)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelHapusJadwal)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapusJadwal)))
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfIdCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapusJadwal)
                    .addComponent(btnCancelHapusJadwal))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
   
    
    public void addListener(ActionListener e){
        btnCancelHapusJadwal.addActionListener(e);
        btnHapusJadwal.addActionListener(e);
    }
    
    private class Controller implements ActionListener {
        
        private SistemLapangan sys;
        public Controller(){
            addListener(this);
        }
        
        public void setModel(SistemLapangan sys){
        this.sys = sys;
        }
        
        public void actionPerformed(ActionEvent ae){
            Object source = ae.getSource();
            String idjadwal = tfIdCari.getText();
            if(source.equals(btnCancelHapusJadwal)){
                mp = new MenuPenjaga(sys);
                mp.setVisible(true);
                setVisible(false);
            }else if(source.equals(btnHapusJadwal)){
                Jadwal hapusjad = sys.cariJadwal(idjadwal);
                try{
                    if(hapusjad == null){
                        JOptionPane.showMessageDialog(null, "ID Tidak Ditemukan");
                    }else {
                        sys.removeJadwal(hapusjad);
                        JOptionPane.showMessageDialog(null, "Jadwal Telah Dihapus");
                        mp = new MenuPenjaga(sys);
                        mp.setVisible(true);
                        setVisible(false);
                    }
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Error Pada Sistem");
                }
            }
        }

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelHapusJadwal;
    private javax.swing.JButton btnHapusJadwal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tfIdCari;
    // End of variables declaration//GEN-END:variables
}
